#!/bin/bash
# Select a file from templates directory, copy to current directory and open using preferred application
if [ -z $TEMPLATES ]; then
       TEMPLATES=$HOME/Templates
fi
if [ $# -eq 0 ] || [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
        echo 'newdoc opens a template file from your $TEMPLATES directory and saves it to current directory with a specified name'
        echo 'If no name is given, the name of the template is used. If the file already exists in your directory, it opens that file without any modifications'
        echo "Usage: newdoc template_name file_name"
        echo 'Example: `newdoc log.txt mylog.txt` creates a file called mylog.txt which is copy of log.txt'
        echo "Options:"
        echo '  -h or --help : Display this message'
        echo '  -l or --list : List all available template files'
        exit
fi
if [ "$1" = "-l" ] || [ "$1" = "--list" ]; then
        echo "Available templates in $TEMPLATES are: "
        ls -1 $TEMPLATES | nl
        exit
fi
if [ -z $2 ]; then
        FNAME=$1
else
        FNAME=$2
fi
# If the file already exists, just open it using default application
if [ -f $FNAME ]; then
        xdg-open $FNAME &
        exit
fi
# If file does not exist and there is a template. copy to current directory and open with default app  
TEMP_FILE="$TEMPLATES""/""$1"
if [ ! -f $TEMP_FILE ]; then
        echo "No template found called $TEMP_FILE does not exist"
        exit
else
        cp $TEMP_FILE $FNAME
        xdg-open $FNAME &
        exit
fi
